IF (OBJECT_ID('dbo.sp_delete_app_param_lkp') IS NOT NULL )
DROP PROCEDURE dbo.sp_delete_app_param_lkp
GO
CREATE PROCEDURE dbo.sp_delete_app_param_lkp
AS
BEGIN
SET COUNT ON

DELETE PARAM_SEQ_NO,PARAM_ID,PARAM_CD,PARAM_NAME,PARAM_VALUE,PARAM_DESC,PARAM_TYPE,PARAM_DATA_TYPE,DELETE_FLG,SOURCE_SYS_ID,CREATED_DT,CREATED_BY,MODIFIED_BY,IS_RESTRICTED
FROM dbo.team.app_param_lkp 
where 
PARAM_SEQ_NO = @PARAM_SEQ_NO, PARAM_ID = @PARAM_ID, PARAM_CD = @PARAM_CD, PARAM_NAME = @PARAM_NAME, PARAM_DESC = @PARAM_DESC, PARAM_TYPE = @PARAM_TYPE, PARAM_DATA_TYPE = @PARAM_DATA_TYPE,
DELETE_FLG = @DELETE_FLG, SOURCE_SYS_ID = @SOURCE_SYS_ID, CREATED_DT = @CREATED_DT, CREATED_BY = @CREATED_BY, MODIFIED_BY =@MODIFIED_BY, IS_RESTRICTED = @IS_RESTRICTED
END
GO

