MERGE [dbo].[Mv_App_param_Lkp] AS TARGET
USING(
SELECT 
   PARAM_SEQ_NO,PARAM_ID,PARAM_CD,PARAM_NAME,PARAM_VALUE,PARAM_DESC,PARAM_TYPE,PARAM_DATA_TYPE,DELETE_FLG,SOURCE_SYS_ID,CREATED_DT,CREATED_BY,MODIFIED_BY,IS_RESTRICTED
   FROM [dbo].[R_App_Param_Lkp]
 AS SOURCE (
	   PARAM_SEQ_NO,PARAM_ID,PARAM_CD,PARAM_NAME,PARAM_VALUE,PARAM_DESC,PARAM_TYPE,PARAM_DATA_TYPE,DELETE_FLAG,SOURCE_SYS_ID,CREDIT_DT,CREATED_DT,CREATED_BY,MODIFIED_BY,IS_RESTRICTED
		ON (TARGET.PARAM_SEQ_NO = SOURCE .PARAM_SEQ_NO)
		WHEN MATCHED THEN
		UPDATE SET PARAM_SEQ_NO = SOURCE .PARAM_SEQ_NO,PARAM_ID = SOURCE.PARAM_ID,PARAM_CD = SOURCE.PARAM_CD, PARAM_NAME = SOURCE. PARAM_NAME, 
		PARAM_VALUE = SOURCE. PARAM_VALUE, PARAM_DESC = SOURCE. PARAM_DESC,  PARAM_TYPE= SOURCE.PARAM_TYPE,PARAM_DATA_TYPE = SOURCE.PARAM_DATA_TYPE,DELETE_FLG = SOURCE.DELETE_FLG,
		SOURCE_SYS_ID = SOURCE.SOURCE_SYS_ID,CREATED_BY = SOURCE.CREATED_BY, MODIFIED_BY = SOURCE.MODIFIED_BY, IS_RESTRICTED = SOURCE.IS_RESTRICTED)

		WHEN NOT MATCHED THEN
		INSERT (PARAM_SEQ_NO,PARAM_ID,PARAM_CD,PARAM_NAME,PARAM_VALUE,PARAM_DESC,PARAM_TYPE,PARAM_DATA_TYPE,DELETE_FLG,SOURCE_SYS_ID,CREATED_DT,CREATED_BY,MODIFIED_BY,IS_RESTRICTED)
	VALUES
	(    SOURCE.PARAM_SEQ_NO,SOURCE.PARAM_ID,SOURCE.PARAM_CD,SOURCE.PARAM_NAME,SOURCE.PARAM_VALUE,SOURCE.PARAM_DESC,SOURCE.PARAM_TYPE,SOURCE.PARAM_DATA_TYPE,SOURCE.DELETE_FLG,SOURCE.SOURCE_SYS_ID,CREATED_DT,SOURCE.CREATED_BY,SOURCE.MODIFIED_BY,SOURCE.IS_RESTRICTED);


	exec sp_dbcmptlevel @dbname = pedge2adm, @new_cmptlevel = 90
